name: 'Github Tag Bump'
description: 'Bump and push git tag on merge'
author: 'Nick Sjostrom'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    LABEL: ${{ inputs.label }}
inputs:
   label:
     description: 'PR label to specify version increment type'
     required: true
     default: ${{fromJSON(github.event.pull_request.labels.*.name)}}
outputs:
  new_tag:
    description: 'Generated tag'
  tag:
    description: 'The latest tag after running this action'
  part:
    description: 'The part of version which was bumped'
branding:
  icon: 'git-merge'  
  color: 'purple'
